# Yes, this should be config.yml, yes, it is a html template, no, i'm not sorry
backend:
  name: github
  repo: {{ config.extra.repo | safe }}
  base_url: {{ config.extra.cms_auth_url | safe }}
local_backend: 
  url: http://172.18.156.44:8081/api/v1

media_folder: "static/images"
public_folder: "/images"
site_url: {{ config.base_url | safe }}
logo_url: {{ get_url(path="assets/logo_compact.svg") }}

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    preview_path: {% raw %}news/{{slug}} {% endraw %}
    create: true
    slug: {% raw %}"{{year}}-{{month}}-{{day}}-{{slug}}" {% endraw %}
    format: toml-frontmatter
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "News Date", name: "date", widget: "datetime", date_format: YYYY-MM-DD, picker_utc: true }

      - {label: "Draft", name: "draft", widget: "boolean", default: {% if config.base_url is containing('draft') %}true{% else %}false{% endif %}}

      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields: 
          - label: "Categories"
            name: "categories"
            widget: "list"
            default: ["Newsletter"]

      - {label: "Body", name: "body", widget: "markdown"}

{% set events = get_section(path="events/_index.md") %}
{% set terms = [] %}
{% for t in events.subsections %}
  {% if t is containing("archive") %}{% continue %}{% endif %}
  {% set term = get_section(path=t) %}
  {% set_global terms = terms | concat(with=term) %}
{% endfor %}

{% set terms = terms | sort(attribute="path") %}
{% for term in terms %}
  {% set_global weeks = [] %}
  {% for w in term.subsections %}
    {% set week = get_section(path=w) %}
    {% set_global weeks = weeks | concat(with=week) %}
  {% endfor %}

  {% set weeks = weeks | sort(attribute="path") %}
  {% for week in weeks %}
  - name: "{{ week.components | join(sep="-") }}"
    label: "{{ term.title }} {{ week.title }}"
    folder: "content/{{ week.components | join(sep="/") }}"
    create: true
    format: toml-frontmatter

    filter:
      pattern: '^.*[^i][^n][^d][^e][^x].md$'

    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Time & Date", name: "date", widget: "string", default: ""}
      - label: Extra
        name: extra
        widget: "object"
        fields:
          - {label: "End Time", name: "end_time", widget: "string", required: false}
          - {label: "Location", name: "location", widget: "string", required: false}
          - {label: "Location URL", name: "location_url", widget: "string", required: false}
          - {label: "Icon", name: "icon", widget: "string", required: false}
          - {label: "Colour", name: "colour", widget: "string", required: true}
          - {label: "Emoji", name: "emoji", widget: "string", required: false}

      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields:
          - label: "Tags"
            name: "tags"
            widget: "list"
            deafult: []
        
      - {label: "Body", name: "body", widget: "markdown"}
  {% endfor %}
{% endfor %}